Blobscan/blobscan

- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/env.mjs
- packages/zod/src/schemas.ts
- pnpm-lock.yaml
This PR validates web app env vars, which were never done before.
The validation can also be bypassed by setting`SKIP_ENV_VALIDATION` or running it as part of a GitHub Actions workflow.
It also removes the `@blobscan/zod` package as nextjs config files doesn't get along with ts files
> chore(web): enable conditional env vars validation

- Dockerfile
- apps/rest-api-server/api/env.ts
- packages/api/src/clients/trpc.ts
- packages/api/src/env.ts
- packages/api/src/router/indexer/indexData/schema.ts
- packages/blob-storage-manager/src/env.ts
- packages/open-telemetry/src/env.ts
- packages/zod/package.json
- packages/zod/src/create-env.ts
- packages/zod/src/index.ts
- packages/zod/src/schemas.ts
- pnpm-lock.yaml
Avoid reinventing the wheel.
This PR updates the codebase to start using t3's env variable validation [package](https://env.t3.gg) instead of our own custom logic.
> Use t3's env var validation package

- apps/rest-api-server/api/env.ts
- apps/web/src/env.mjs
- packages/blob-storage-manager/src/env.ts
- packages/zod/src/schemas.ts
We use this workaround instead of `z.coerce.boolean.default(false)` because it considers as "true" any value different than "false" (including the empty string).
> Bring booleanSchema back

- apps/web/src/pages/blob/[hash].tsx
- apps/web/src/utils/text.ts
ethers.js implementation raises an exception as soon as one of the characters cannot be utf-8 decoded
See https://blobscan.com/blob/0x01eb50cbcd04004b89d42cbaeed19b9728d7498ada756c675f4f658e4d0f847a
> fix: add our own function to convert a hexadecimal string to utf-8

- apps/web/package.json
- apps/web/src/components/BlobGasUsage.tsx
- apps/web/src/components/Charts/Block/DailyAvgBlobFeeChart.tsx
- apps/web/src/components/Charts/Block/DailyAvgBlobGasPriceChart.tsx
- apps/web/src/components/Charts/Block/DailyBlobFeeChart.tsx
- apps/web/src/components/PercentageBar.tsx
- apps/web/src/pages/block/[id].tsx
- apps/web/src/pages/tx/[hash].tsx
- apps/web/src/utils/ethereum.ts
- apps/web/src/utils/number.ts
- apps/web/src/utils/text.ts
- packages/config/tailwind/colors.ts
- pnpm-lock.yaml
Fixes https://github.com/Blobscan/blobscan/issues/133
Changes:
* Do not format **Block and Slot number** with commas, as in other block explorers. It also makes it easier to copy-paste.
* **Blob Gas Price** now is shown in ether and gwei for easier conversions
* **Removed 'Total' from metric names**
* **Blob Gas Used** now shows the percentage of blob space used and target blob gas (reminder: maximum blobs per block is 6, while target is 3, similar to how the gas fee work)
* Show number of blobs next to **Blob Size**
* Show **Blob Gas Limit**
**BEFORE THIS PR:**
**AFTER THIS PR:**
> Block details

- apps/web/src/components/Cards/Card.tsx
- apps/web/src/components/Displays/BlobGasUsageDisplay.tsx
- apps/web/src/components/Displays/EtherUnitDisplay.tsx
- apps/web/src/components/InfoGrid.tsx
- apps/web/src/components/Layouts/DetailsLayout.tsx
- apps/web/src/hooks/useBreakpoint.ts
- apps/web/src/pages/block/[id].tsx
- apps/web/src/pages/tx/[hash].tsx
- apps/web/src/utils/ethereum.ts
It adds the following changes to the details pages:
1. Improve ether unit fields by displaying both `ether` and `gwei` amounts.
2. Polish skeleton loading display and fix overflowing problem on mobile view
> fix(web): details view improvements

- apps/web/vercel.json
We can reintegrate it, as we can now safely apply Prisma migrations to PRs with a specific database instance set up for Vercel's preview environment.
> chore: reintegrate Prisma migration execution into vercel build flow

- .changeset/config.json
- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
- tooling/github/package.json
Versioning packages on master required us to re-merge versioning commits back to next which can make commit history really convoluted.
This PR changes changeset's  base branch to next so we do the versioning in that branch before merging to master.
It also adds `@changesets/changelog-github` to improve changelogs formatting
> chore: changeset retargeting

- .changeset/blue-geese-teach.md
- .changeset/flat-eagles-fail.md
- apps/web/src/pages/blob/[hash].tsx
- apps/web/src/types/routers.ts
- apps/web/src/utils/ethereum.ts
- packages/api/src/routers/blob/getByBlobId.schema.ts
- packages/api/src/routers/blob/getByBlobIdFull.ts
- packages/api/src/routers/blob/index.ts
- packages/api/test/__snapshots__/blob.test.ts.snap
- packages/api/test/blob.test.ts
> feat(web): add back navigation from blob to transactions

- .changeset/happy-suits-obey.md
- .changeset/slow-dancers-study.md
- .changeset/weak-bags-grow.md
- clis/blob-propagation-jobs-cli/src/commands/count.ts
- clis/blob-propagation-jobs-cli/src/commands/create.ts
- clis/blob-propagation-jobs-cli/src/commands/get.ts
- clis/blob-propagation-jobs-cli/src/commands/index.ts
- clis/blob-propagation-jobs-cli/src/commands/remove.ts
- clis/blob-propagation-jobs-cli/src/commands/retry.ts
- clis/blob-propagation-jobs-cli/src/main.ts
- clis/blob-propagation-jobs-cli/src/types.ts
- clis/blob-propagation-jobs-cli/src/utils.ts
- clis/blob-propagation-jobs-cli/src/utils/index.ts
- clis/blob-propagation-jobs-cli/src/utils/jobs.ts
- clis/blob-propagation-jobs-cli/src/utils/options-defs.ts
- clis/blob-propagation-jobs-cli/test/commands/count.test.ts
- clis/blob-propagation-jobs-cli/test/commands/create.test.ts
- clis/blob-propagation-jobs-cli/test/commands/remove.test.ts
- clis/blob-propagation-jobs-cli/test/commands/retry.test.ts
- clis/blob-propagation-jobs-cli/test/helpers.ts
- package.json
This PR adds the following commands:
```
Count Command
Count propagation jobs. 
Options
-h, --help          Print this usage guide.                                   
-q, --queue queue   Queue to get the jobs count of. Valid values are          
finalizer, file_system, google, postgres, swarm
Get Command
Get propagation jobs. 
Options
-h, --help                 Print this usage guide.                            
-b, --blobHash blob-hash   Hash of the blob to get the job of                 
-q, --queue queue          Queue to get the jobs from. Valid values are       
finalizer, file_system, google, postgres, swarm    
--fromDate from-date       Date from which to retrieve blobs to get the jobs  
of.                                                
--toDate to-date           Date to which …
```
> feat(blob-propagation-jobs-cli): add `count` and `get` command

- .changeset/light-adults-shake.md
- packages/db/prisma/extensions/base.ts
> fix(db): fix find latest block extension function

- packages/blob-storage-manager/src/storages/SwarmStorage.ts
- packages/env/index.ts
Introduce new environment variable SWARM_DEFERRED_UPLOAD.
Documentation has been updated at https://github.com/Blobscan/blobscan/pull/427
We want to test deferred uploads again, otherwise Swarm storage won't keep in sync at the rates the new blobs are received.
> feat: allow configuring swarm upload deferred or not

- .changeset/lemon-worms-clap.md
- .changeset/modern-walls-complain.md
- apps/web/src/components/Cards/SurfaceCards/BlobTransactionCard.tsx
- apps/web/src/pages/tx/[hash].tsx
- packages/api/src/routers/block/common/selects.ts
- packages/api/src/routers/block/common/serializers.ts
It solves #438.
This PR displays the recently-added transaction index on the transaction details page.
It also modifies the API to return a block’s transactions sorted by the newly added transaction index.
> feat: display transaction index

- .changeset/fuzzy-deers-glow.md
- packages/api/src/middlewares/withFilters.ts
- packages/api/src/routers/blob/getAll.ts
- packages/api/src/routers/block/getAll.ts
- packages/api/src/utils/schemas.ts
- packages/api/test/__snapshots__/blob.test.ts.snap
- packages/api/test/__snapshots__/block.test.ts.snap
- packages/api/test/__snapshots__/tx.test.ts.snap
- packages/api/test/helpers.ts
It introduces a new feature that allows to filter entities (blobs, blocks or transactions) that have no `rollup` field set by providing the `null` value.
It resolves #381 
Currently, it's only possible to retrieve entities by a specific rollup or all.
> feat: add filter to retrieve entities that have/contain no rollup 

- .changeset/fresh-walls-learn.md
- packages/api/src/middlewares/withExpands.ts
- packages/api/src/routers/block/common/selects.ts
- packages/api/src/routers/block/common/serializers.ts
- packages/api/src/routers/block/getAll.ts
- packages/api/test/__snapshots__/blob.test.ts.snap
- packages/api/test/__snapshots__/block.test.ts.snap
This PR move the transaction `rollup`, `index` and blob `index` fields to the expandable fields in the returned block as this   should be treated as expandable. If no expand query parameter is provided, only return the relational resource IDs.
> fix(api): move tx rollup, tx index and blob index fields to expandable fields in block retrieval

- .changeset/hip-readers-wait.md
- .changeset/quick-peas-lay.md
- apps/web/src/pages/blob/[hash].tsx
- packages/api/src/middlewares/withExpands.ts
- packages/api/src/routers/blob/common/serializers.ts
- packages/db/prisma/migrations/20240716151437_make_blob_proof_field_mandatory/migration.sql
- packages/db/prisma/migrations/20240716152934_create_blob_proof_index/migration.sql
- packages/db/prisma/schema.prisma
- packages/db/test/extensions/stats-extension.test.fixtures.ts
It makes the blob `proof` field on the `Blob` prisma model mandatory
We have populated this field in all blobscan instances so now we can make mandatory
> feat: make blob proof field mandatory

- .changeset/strange-pianos-fetch.md
- packages/api/package.json
- packages/api/src/routers/blob/getBlobDataByBlobId.ts
- packages/api/src/routers/blob/index.ts
- packages/api/src/utils/blob.ts
- packages/api/src/utils/schemas.ts
- packages/api/test/__snapshots__/blob.test.ts.snap
- packages/api/test/blob.test.ts
- packages/api/test/test-suites/schemas.ts
- packages/db/test/extensions/stats-extension.test.ts
- packages/test/src/fixtures/index.ts
- packages/test/src/fixtures/postgres/data.json
- pnpm-lock.yaml
It adds a new procedure to the api to retrieve the blob data given a blob identifier which can be a blob's versioned hash or kzg commitment.
This PR is related to #446.  By implementing an OpenAPI-supported procedure to retrieve blob data, the API can now return URLs for retrieving blob data from internal storage systems such as Postgres or the file system, alongside other blob data references when retrieving a single blob or a series of blobs.
> feat(api): add `getBlobDataByBlobId` procedure

- apps/web/package.json
- apps/web/src/components/EthIdenticon.tsx
- pnpm-lock.yaml
It replaces the `ethers` library being used in the frontend by `viem`
> chore(web): replace `ethers` by `viem`

- packages/env/index.ts
This variable was being displayed twice
> fix: remove dupe env var in cli banner

- .changeset/tiny-dancers-live.md
- apps/web/src/components/Table/index.tsx
- apps/web/src/pages/txs.tsx
It resolves #451
Migrate the current 'transaction view' using a transaction card list to the new `PaginatedTable` component
> feat(web): replace list of `TransactionCard` by new `PaginatedTable` on the transactions view

- apps/web/src/pages/search.tsx
- packages/api/src/index.ts
- packages/api/src/routers/search/byTerm.schema.ts
- packages/api/src/routers/search/byTerm.ts
The search bar currently only works if the suggestions are loaded. If the suggestions aren't loaded and you press the `enter` key, you'll be redirected to an error 500 page after a few seconds.
The problem occurred because an invalid `trpc context` was being created inside `getServerSideProps` in the `search.tsx` file.
As we are already on the server, there is no need to recreate a `trpc helper` each time someone visits `\search`. We can simply call the search function directly. To achieve this, I refactored the search functionality out of the `trpc query` so that we can use the search function both inside and outside the query.
https://github.com/Blobscan/blobscan/issues/66#issuecomment-2057009689
If you are on the main branch and you try to search for something, you will encounter this …
> fix: Fix search

- apps/web/src/utils/ethereum.ts
- apps/web/src/utils/number.ts
This change addresses an error in the `calculatePercentage` function that occurred when using synthetic data generated by the data generator. The error message was:
```RangeError: The number 21460778973.687706 cannot be converted to a BigInt because it is not an integer```
To resolve this issue, I made the following changes:
1. Updated functions that previously accepted `BigIntLike` parameters to exclusively accept `bigint`.
2. Removed the `BigIntLike` type entirely from the codebase.
3. Added `numberToBigInt`
These modifications ensure type consistency and prevent potential conversion errors when working with large numbers.
This function takes two `BigIntLike`. Initially, I considered implementing a more robust conversion, which would have introduced some overhead. However, upon further …
> refactor: Remove BigIntLike

- apps/docs/src/app/docs/environment/page.md
- packages/env/index.ts
Change default value for the SWARM_DEFERRED_UPLOAD variable.
We had some problems in the past with the swarm bee client and deferred uploads, so we set it to False. It looks like these issues are gone since the bee v2.0.0 release so it is safe to set it back to true by default. It is also required in order to keep the swarm storage in sync with the blobs that are processed.
> Make SWARM_DEFERRED_UPLOAD default to true

- packages/db/package.json
- pnpm-lock.yaml
Fix prisma version mismatch between @prisma and @prisma-client
The warning was being shown in the build logs:
```
@blobscan/db:db:generate: warn Versions of prisma@5.5.2 and @prisma-client@5.17.0 don't match.
@blobscan/db:db:generate: This might lead to unexpected behavior.
@blobscan/db:db:generate: Please make sure they have the same version.
```
> ci: Fix prisma version mismatch between @prisma and @prisma-client

- .changeset/seven-gorillas-deny.md
- apps/web/src/utils/pagination.ts
The dropdown change doesn't update the table page size in the new `<PaginatedTable />` component as a bug introduced in `patination` utils
> fix: 'Display Items' dropdown in `PaginatedTable` change not working

- .changeset/chilled-frogs-battle.md
- apps/web/src/components/Cards/MetricCard.tsx
- apps/web/src/components/Displays/EtherUnitDisplay.tsx
- apps/web/src/components/ExplorerDetails.tsx
- packages/eth-format/index.ts
- packages/eth-format/test/eth-units.test.ts
Updated `EtherUnitDisplay` to accept `bigint`, `number`, or `string` for `amount` prop
Closes #521
> Ether unit allow string number

- .changeset/two-keys-divide.md
- packages/api/src/routers/indexer/indexData.utils.ts
- packages/api/test/indexer.test.fixtures.ts
- packages/api/test/indexer.test.ts
It corrects the indexing procedure to resolve the rollup address from the transactions' sender rather than the receiver.
> Fix rollup resolution

- .changeset/witty-steaks-rest.md
- apps/web/src/components/Cards/MetricCard.tsx
Resolved homepage metrics display overflow issue
Closes #508
Before:
After:
> Fix metrics display overflow

- apps/web/src/components/Cards/MetricCard.tsx
Update MetricCard to use `findBestUnit` for Ethereum values
Before:
After:
> feat: Update MetricCard to use findBestUnit for Ethereum values

- .changeset/quiet-islands-greet.md
- apps/web/src/components/AppLayout/BottomBarLayout/index.tsx
- apps/web/src/components/AppLayout/TopBarLayout/TopBar.tsx
- apps/web/src/components/AppLayout/TopBarLayout/index.tsx
- apps/web/src/components/ExplorerDetails.tsx
`Last Synced Slot` and `Swarm Data Expiry` items from the `ExplorerDetails` have been moved to the footer
Closes #517 
| Top  | Bottom   |  
|---|---|
| <img width="366" alt="image" src="https://github.com/user-attachments/assets/7785a50e-001a-449a-9a26-7ef7dabf5aa8">  | <img width="651" alt="image" src="https://github.com/user-attachments/assets/93855e77-5177-4ccb-a59c-a0233c44130f">  |  
| <img width="437" alt="image" src="https://github.com/user-attachments/assets/8e59d276-c48f-452b-b1b3-b0ef93b0e348"> |  <img width="445" alt="image" src="https://github.com/user-attachments/assets/f3752815-f050-427d-9211-a1deaa0b5045"> |
> refactor: move `Last Synced Slot` and `Swarm Data Expiry` to footer

- packages/db/prisma/migrations/20240909234614_remove_redundant_block_number_index/migration.sql
- packages/db/prisma/migrations/20240909234808_add_rollup_index/migration.sql
- packages/db/prisma/migrations/20240910000321_add_tx_sender_receiver_indexes/migration.sql
- packages/db/prisma/schema.prisma
Resolves #547 
This PR introduces the following indexes to the `Transaction` model:
- `(category, rollup, block_number, index)`: This index allows efficient filtering by category and rollup, while ensuring the results are sorted by `block_number` and `index` without needing an additional sorting step.
- `(fromId, block_number, index)`: Similar to the above, this index enables filtering by the transaction sender (`fromId`), while also returning results sorted by `block_number` and `index`.
- `(toId, block_number, index)`: Like the previous index, but this one allows filtering by the transaction receiver (`toId`), with results also sorted by `block_number` and `index`.
Some filtering queries on the client have been experiencing timeouts, particularly when filtering blobs by rollup. This …
> perf(db): add rollup indexes

- .changeset/happy-hounds-join.md
- apps/web/src/components/ExpandableContent.tsx
Fixed the issue where the "Show more" message was displayed incorrectly when the blob data container was opened and closed. The message now properly toggles between "Show more" when the container is closed and "Show less" when the container is open.
Closes #565
Before:
> Fix show more

- .changeset/rotten-llamas-pull.md
- apps/web/src/components/CopyToClipboard.tsx
- apps/web/src/components/InfoGrid.tsx
Copyable values overflow viewport on small screens
Closes [#548](https://github.com/Blobscan/blobscan/issues/548)
Before:
After:
> fix(web): Copyable values overflow viewport on small screens

- apps/web/src/components/Charts/Blob/DailyBlobSizeChart.tsx
- apps/web/src/components/Charts/Blob/DailyBlobsChart.tsx
- apps/web/src/components/Charts/Block/DailyAvgBlobFeeChart.tsx
- apps/web/src/components/Charts/Block/DailyAvgBlobGasPriceChart.tsx
- apps/web/src/components/Charts/Block/DailyBlobFeeChart.tsx
- apps/web/src/components/Charts/Block/DailyBlobGasComparisonChart.tsx
- apps/web/src/components/Charts/Block/DailyBlobGasUsedChart.tsx
- apps/web/src/components/Charts/Block/DailyBlocksChart.tsx
1. Display 3.5M wei instead of 3,500,000 wei
2. Display `Daily Avg. Blob Fee` and `Daily Avg. Blob Gas Price` as line charts by default.
3. Use the best unit in `Daily Blob Gas Expenditure Comparison`.
Closes [#540](https://github.com/Blobscan/blobscan/issues/540)
Before:
After:
Before:
After:
Before:
After:
> feat: Improvements in stats page

- .changeset/dirty-seals-appear.md
- apps/web/src/components/AppLayout/TopBarLayout/index.tsx
The right hamburger menu affected the center placement of the Explorer Details. Adding some space on the left side of the details equal to the width of the menu icon should fix the problem.
Closes #556 
Fixes #517
> fix: Top `ExplorerDetails` not horizontally center aligned in small screens

- .changeset/selfish-melons-guess.md
- apps/web/src/pages/blobs.tsx
- packages/api/src/routers/blob/getAll.ts
Fixed blob pagination count
Closes [#535](https://github.com/Blobscan/blobscan/issues/535)
[#528](https://github.com/Blobscan/blobscan/issues/528)
Before:
After:
> fix(web): fixed blob pagination count

- packages/api/src/routers/blob/getAll.ts
- packages/api/src/routers/tx/getAll.ts
- packages/db/prisma/migrations/20240928161343_swap_transaction_fork_composite_index_columns/migration.sql
- packages/db/prisma/migrations/20240929151029_update_tx_indexes/migration.sql
- packages/db/prisma/schema.prisma
It applies the following changes:
- Swap the composite key of the `TransactionFork` model from (`hash`,`blockHash`) to (`blockHash`,`hash`) so that an index on `blockHash` is created.
- Replace `blockNumber` with `blockTimestamp` in the indexes of the `Transaction` model to leverage this for date filtering and normal sorting.
- Use `blockNumber` as sort column only when that filter has been provided in txs and blobs pages
> perf(db): update indexes

- apps/web/src/components/Cards/SurfaceCards/SurfaceCardBase.tsx
This update refactors the `SurfaceCardBase` component to improve its flexibility and simplify style overrides:
1. Integration of `twMerge`: The `SurfaceCardBase` component now leverages `twMerge` to allow easy style overrides. By using `twMerge`, custom styles passed via `className` will correctly override default styles.
2. Removal of `truncateText`: The `truncateText` prop has been removed, as it is not used anywhere in the codebase. With the introduction of `twMerge`, text truncation and other styles can now be customized or overridden by passing a `className`.
This change maintains the same component behavior while enhancing the ability to customize styles.
> refactor: Simplify SurfaceCardBase component

- .changeset/famous-dodos-fetch.md
- packages/rollups/src/index.ts
- packages/rollups/test/rollups.test.ts
It adds missing Sepolia's rollup sequencer addresses for the following: arbitrum, base, Linea and optimism.
> feat(rollups): add missing sepolia rollups

- .changeset/fast-starfishes-live.md
- .changeset/six-wasps-perform.md
- apps/web/src/pages/tx/[hash].tsx
This PR hides the decoded fields section when there is no decoded data to be shown and remove "transaction" from the header
> fix(web): add decoded fields section fixes

- .changeset/strong-masks-remain.md
- apps/web/src/components/Badges/Badge.tsx
- apps/web/src/components/Badges/StatusBadge.tsx
- apps/web/src/components/SearchInput/SearchResults.tsx
- packages/api/src/routers/search/byTerm.ts
- packages/api/test/search.test.ts
Adds a `reorg` label to reorged slots/blocks search results
Closes #406
Before:
After:
> fix(web): add a "reorg" label to reorged slots/blocks search results

- .changeset/nine-trees-eat.md
- packages/api/src/middlewares/withFilters.ts
- packages/api/src/routers/blob/getCount.ts
- packages/api/src/routers/tx/getCount.ts
- packages/api/src/utils/count.ts
- packages/api/test/blob.test.ts
- packages/api/test/helpers.ts
- packages/api/test/test-suites/filters.ts
- packages/api/test/tx.test.ts
- packages/dayjs/src/date.ts
- packages/db/prisma/extensions/stats.ts
- packages/db/test/helpers/suites/daily-stats.ts
- packages/test/src/fixtures/index.ts
It optimizes the retrieval of element counts when filters are applied. By obtaining the total number of elements from the stats tables—specifically when filtering by rollup, category, or timestamp—we can utilize data from the overall or daily stats tables.
> perf(api): optimise count retrieval

- .changeset/fresh-poets-joke.md
- apps/web/src/components/FeedbackWidget.tsx
- apps/web/src/components/FeedbackWidget/Emoji.tsx
- apps/web/src/components/FeedbackWidget/FeedbackCard.tsx
- apps/web/src/components/FeedbackWidget/FeedbackWidget.tsx
- apps/web/src/icons/chat.svg
- apps/web/src/icons/close.svg
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/api/feedback/enabled.ts
- apps/web/src/pages/api/feedback/index.ts
Suggest opening a new issue in Feedback form
Closes #512
Before:
After:
Before:
After:
> chore: Suggest opening a new issue in Feedback form

- .changeset/smart-bears-sin.md
- apps/web/src/components/SearchInput/SearchResults.tsx
Display `id` in `SearchResultItem` when label is absent
Closes #618
> Display `id` in `SearchResultItem` when label is absent

- apps/docs/src/app/docs/running-blobscan-kurtosis/page.md
Fixed a typo in the `page.md` file. Removed the redundant word "up" in the sentence:  
**"spin up up a local PoS Ethereum testnet..."** → **"spin up a local PoS Ethereum testnet..."**
Fixing the typo improves the readability of the documentation and reduces potential confusion.
> Minor Documentation Update: Typo Correction

- .changeset/brown-emus-hunt.md
- .changeset/khaki-rules-applaud.md
- .changeset/rotten-bears-bathe.md
- packages/api/src/routers/indexer/handleReorgedSlots.ts
- packages/api/src/routers/indexer/indexData.ts
- packages/api/test/indexer.test.ts
- packages/db/prisma/migrations/20241119092259_add_address_category_info_fks/migration.sql
- packages/db/prisma/migrations/20241120051254_add_block_number_reference_indexes/migration.sql
- packages/db/prisma/schema.prisma
**It builds on top of #635** 
This PR introduces improvements to the reorg handling logic:
- It removes forked transaction records from blocks that were flagged as reorged and later reindexed.
- It clears block number references from records associated with reorged blocks. This involves setting the `firstBlockNumber` fields to `null` on both the address category and blob models.
> fix(api): add reorg handling fixes

- apps/web/src/components/Dropdown/Option.tsx
- apps/web/src/components/Dropdown/index.tsx
- apps/web/src/components/Filters/RollupFilter.tsx
- apps/web/src/components/Filters/index.tsx
- packages/rollups/src/index.ts
- packages/rollups/test/rollups.test.ts
It resolves an issue where the rollup filter wasn't filtering rollups with multiple blob submitter addresses correctly.
#615
> fix(web): add support for filtering rollups with multiple blob submitter addresses

- .changeset/eighty-clouds-end.md
- apps/web/src/components/Filters/RollupFilter.tsx
- apps/web/src/components/Filters/index.tsx
It fixes an issue where the rollup filter wasn't being properly set given a `from` query param containing several addresses
> fix(web): set Rollup filter for multiple `from` addresses from query params

- .vscode/extensions.json
Removes unused `expo-tools` extension from recommendations
> chore: removes unused expo-tools extension from recommendations

- packages/db/package.json
- packages/db/prisma/seed/DataGenerator.ts
- packages/db/prisma/seed/main.ts
- pnpm-lock.yaml
It does the following:
- It fixes an issue where the seed script wasn't creating the address category info db entities correctly.
- It also generates blob data for every created blob.
- It improves the script's logs
- It replaces `ts-node` by `tsx` as former resolves modules to commonjs which was giving problems with certain esm-only packages (e.g. `ora`)
> chore(db): fix seed script

- .changeset/quick-suns-switch.md
- apps/web/src/components/Displays/StandardEtherUnitDisplay.tsx
To avoid the overflow with big values, we can set the display information into column for smaller devices
Closes #638 
| BEFORE | AFTER  |
|----------|----------|
| <img width="341" alt="image" src="https://github.com/user-attachments/assets/3b4deaa1-ba6b-405c-aafc-4c17cee68be9"> | <img width="340" alt="image" src="https://github.com/user-attachments/assets/3ce2dc89-f25b-42d6-9a8d-c3d42d1018dc"> |
> fix: ether display overflow on small screens in Transaction details page

- .changeset/proud-cars-try.md
- apps/web/src/pages/blocks.tsx
The `blocks` table only shows unique rollups in the list. To check-in details the `rollup` associated with each `transaction` the user can check the expanded table for each row.
Closes #659 
| BEFORE | AFTER |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/710cdf0e-df6a-4fd0-b749-365b1019ff00)  | <img width="238" alt="image" src="https://github.com/user-attachments/assets/9022825a-0a07-4502-9ae0-4fe587cdedcc">  |
> Simplify block table rollups list

- .changeset/hip-suits-buy.md
- apps/web/src/components/Cards/ChartCard.tsx
The charts from the home page are now aligned with the stats data.
Closes #660 
| BEFORE | AFTER |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/4988a498-4565-4f9d-af79-3e76912dfcaa) | <img alt="image" src="https://github.com/user-attachments/assets/004bb410-7507-41ad-a68f-906fcba04557">  |
> Fix home page charts misalignment

- apps/web/src/pages/_app.tsx
- packages/api/src/context.ts
This update fixes the client-side capturing of `PostHog` events and adds additional data to the metadata.
The issue with client-side `PostHog` event capturing arose because we were attempting to read a server-side environment variable within the `loaded` function.
Additionally, we now save the network name, as well as the `pathname` and `queryString` in the `PostHog` metadata.
#650
> fix: fixes client side PostHog events capturing and adds extra data to the metadata

- apps/docs/src/app/docs/running-blobscan-kurtosis/page.md
- packages/db/CHANGELOG.md
- packages/syncers/CHANGELOG.md
This PR addresses multiple typo and grammar corrections across various files, including the following:
- Corrected "one liners" to "one-liners" in the `page.md` file.
- Fixed the phrase "non unique" to "non-unique" in the `CHANGELOG.md` for `db` package.
- Removed redundant "to" in the `CHANGELOG.md` for `syncers` package.
- Reworded "where" to "when" for time-related references in `CHANGELOG.md` for `syncers` package.
These changes ensure better clarity and adherence to grammar rules.
> Fix typos and grammar in documentation and changelogs

- apps/docs/src/app/page.md
I noticed that the word "storage" was being used incorrectly in the plural form in several places across the code. As we know, "storage" is an uncountable noun in English and should not be pluralized. I've gone ahead and corrected this by changing the instances where it appeared in the plural form to the correct singular form.
> docs: Fix pluralization issue Update page.md

- apps/web/CHANGELOG.md
This pull request corrects the typo in the `CHANGELOG.md` file by changing "Standarized" to "Standardized" in the following entry:
- [#598](https://github.com/Blobscan/blobscan/pull/598) [`05bdc1d`](https://github.com/Blobscan/blobscan/commit/05bdc1d0645bf510df211eb8c0d2bda63ffd1c76) Thanks [@PJColombo](https://github.com/PJColombo)! - **Standardized** y-axis units and displayed full amounts on tooltips on charts.
> Fix typo Update CHANGELOG.md

- packages/api/CHANGELOG.md
This pull request corrects the typo "posibility" to "possibility" in the `CHANGELOG.md` file.
- Replaced "posibility" with "possibility."
> Fix typo CHANGELOG.md

- packages/api/src/context.ts
Include host in $current_url
#650
> fix: include host in $current_url

- apps/docs/src/app/docs/running-blobscan-k8s/page.md
- apps/web/sentry.client.config.ts
Changes:
1. apps/docs/src/app/docs/running-blobscan-k8s/page.md
- clusters -> cluster
Reason: Fixed plural to singular as referring to single Kubernetes cluster setup
2. apps/web/sentry.client.config.ts  
- users -> user
Reason: Corrected plural to singular in comment as it describes single user action
> Fix Grammar Issues in Documentation and Comments

- .changeset/slimy-fishes-roll.md
- apps/web/src/components/PaginatedTable/index.tsx
- apps/web/src/components/TimestampToggle.tsx
- apps/web/src/pages/blobs.tsx
- apps/web/src/pages/blocks.tsx
- apps/web/src/pages/txs.tsx
Added button to toggle between relative time and date-time format
Closes #648
Dark mode:
> Toggle timestamp

- .changeset/unlucky-chairs-smell.md
- apps/docs/src/app/docs/environment/page.md
- packages/api/src/utils/serializers.ts
- packages/env/index.ts
This PR updates the returned blob data storage weavevm references by replacing the hardcoded base url for `WEAVEVM_STORAGE_API_BASE_URL` env var
It also sets a default value for `WEAVEVM_STORAGE_API_BASE_URL`
> chore(api): replace hardcoded weavevm base url

- apps/docs/src/app/docs/storages/page.md
A typo in the name of the technology. It should be `WeaveVM` (with uppercase "VM") since it stands for "Virtual Machine."
> docs: Fix typo in technology name Update page.md

- apps/docs/src/app/docs/codebase-overview/page.md
I noticed that the article "the" was incorrectly used before "Blobscan's" in the documentation. Since "Blobscan" is a proper noun (the project's name), the article is unnecessary.
I've removed it to ensure grammatical accuracy and consistency.
> docs: fix incorrect use of "the" before "Blobscan's" Update page.md

- apps/docs/src/app/docs/clis/page.md
In the "Remove Command" section, the description for the `-q, --queue` option incorrectly states that it is used to "retry failed jobs." However, this command is intended for removing tasks, not retrying them.
I've updated the description to accurately reflect its purpose:  
```bash
Queue to remove failed jobs from. Valid values are finalizer, google, postgres or swarm.
```
> docs: Fix incorrect description for -q, --queue in page.md

- packages/api/CHANGELOG.md
1. **File:** `/packages/api/CHANGELOG.md`
- Fixed `Splited` to `Split` (Line 346)
- Enhanced the clarity and professionalism of the documentation.
- Fixed minor grammatical issues for better understanding.
> Fixed typos

- .changeset/early-shrimps-guess.md
- packages/api/src/routers/block/common/index.ts
- packages/api/src/routers/block/common/queries.ts
- packages/api/src/routers/block/getByBlockId.ts
- packages/api/src/routers/block/getBySlot.ts
- packages/api/src/routers/block/index.ts
- packages/api/test/__snapshots__/block.test.ts.snap
- packages/api/test/block.test.ts
- packages/zod/src/schemas.ts
It adds a new procedure `getBySlot` which enables consumers to fetch blocks by their slot. It also exposes the procedure as a REST endpoint.
> feat(api): add support for fetching blocks by slot

- packages/api/src/routers/block/getByBlockId.ts
- packages/api/src/routers/block/getBySlot.ts
It fixes `getByBlockId` procedure invalid schema issue and add missing output schema to `getBySlot` procedure.
> fix(api): resolve `getByBlockId` and `getBySlot` procedure `trpc-openapi` issues

- .changeset/big-bags-warn.md
- apps/web/src/pages/stats/index.tsx
- packages/api/src/routers/stats/getDailyStats.ts
Stats bar charts are displayed backwards
Closes  #687
> Fix stats order

- packages/env/index.ts
- packages/zod/src/schemas.ts
This PR refactors the logic used to conditionally require environment variables based on other settings. Previously, we used a function called `conditionalRequiredSchema`, which was exclusively invoked by `requiredStorageConfigSchema`. The logic was convoluted and difficult to follow. This refactor simplifies the logic and makes it more intuitive.
- Replaced conditionalRequiredSchema with a more direct approach using superRefine in Zod schemas.
- Introduced a new utility function requireIfEnvEnabled, which checks if an environment variable is enabled (process.env[<env_name>] === "true") and enforces that another field is required based on this.
- Updated the schema for several environment variables like SWARM_STORAGE_ENABLED and GOOGLE_STORAGE_ENABLED to use this new approach for …
> refactor(env): replace conditionalRequiredSchema and requiredStorageConfigSchema with requireIfEnvEnabled

- packages/env/index.ts
It makes `GOOGLE_STORAGE_API_ENDPOINT` optional again, as it’s used only for development.
> chore: make `GOOGLE_STORAGE_API_ENDPOINT` optional

- .changeset/mighty-flies-occur.md
- packages/api/src/routers/block/getBySlot.ts
It removes `sort` query param from `getBySlot` procedure
> fix(api): remove sort query param

- packages/blob-storage-manager/src/instrumentation.ts
Noticed a typo in `updateBlobStorageMetrics`: the variable was named `counterAttributtes` instead of `counterAttributes`. Fixed it to use the correct spelling.
No functional changes, just making the code a bit cleaner.
> chore: fix typo in variable name

- apps/docs/src/app/docs/testing/page.md
- packages/api/test/indexer.test.ts
Fixed a broken link in the documentation and corrected a typo in the test file.  
- **`page.md`** – Updated an outdated script link.  
- **`indexer.test.ts`** – Fixed a typo in a test description (`cleaing` → `cleaning`).  
N/A  
N/A
> fix: documentation link and typo

- clis/blob-propagation-jobs-cli/test/commands/retry.test.ts
- packages/api/test/__snapshots__/blob.test.ts.snap
- packages/api/test/__snapshots__/block.test.ts.snap
- packages/api/test/__snapshots__/tx.test.ts.snap
- packages/api/test/helpers.ts
- **Fixed spelling in `retry.test.ts`**:
- `versionesHash1`, `versionesHash2`, `versionesHash3` → `versionsHash1`, `versionsHash2`, `versionsHash3` in job versioned hashes.
- **Updated API snapshot test files (`blob.test.ts.snap`, `block.test.ts.snap`, `tx.test.ts.snap`)**:
- Corrected `"specificed"` → `"specified"` in multiple test cases to ensure proper terminology.
- **Fixed spelling in `helpers.ts`**:
- `"specificed"` → `"specified"` in block filter test descriptions.
> Fix spelling errors in API snapshots and retry command test cases

- .changeset/silver-sloths-kick.md
- apps/rest-api-server/src/index.ts
- apps/rest-api-server/src/morgan.ts
It increases maximum allowed request body size to 3mb
Following the recent Pectra upgrade, indexing request body sizes have increased significantly, as up to nine blobs can now be indexed (~2.36mb).
> fix(rest-api-server): increase request body size limit

- .changeset/mean-rivers-study.md
- .changeset/ninety-zebras-attack.md
- apps/web/src/components/Cards/ChartCard.tsx
- apps/web/src/components/Charts/Blob/index.ts
- apps/web/src/components/Charts/Block/DailyAvgBlobGasPriceChart.tsx
- apps/web/src/components/Charts/DailyBlobsPerRollupChart.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/types/routers.ts
- packages/api/src/middlewares/withTimeFrame.ts
- packages/api/src/routers/stats/getRollupDailyStats.ts
- packages/api/src/routers/stats/index.ts
- Show last 30 days instead of 15 days of Gas Expenditure on Home page
- Replace `Daily Transactions` by `Blobs per Rollup` in Home page
Closes #616
> feat: update home charts

- packages/api/src/procedures/public.ts
TRACES_ENABLED variable is not honored in rest-api-server
Closes  #749
> fix: TRACES_ENABLED variable is not honored in rest-api-server

- packages/api/src/routers/blob/getAll.ts
- packages/api/src/routers/block/getAll.ts
- packages/api/src/routers/tx/getAll.ts
…finitions
Break down the TRPC procedure input schemas into smaller input definitions to prevent excessively deep type instantiation TS error.
> refactor(api): breakdown procedure input schema into smaller input schemas

- packages/api/src/instrumentation.ts
Add three new Prometheus metrics to expose indexing progress:
- blobscan_latest_block_number: Tracks the latest block number indexed
- blobscan_latest_slot: Tracks the latest slot indexed
- blobscan_last_block_index_timestamp: Timestamp of the last block indexed by Blobscan
These metrics help monitor the indexing status of Blobscan and can be used for alerting on indexing delays or gaps.
> feat(metrics): add Prometheus metrics for latest block and slot

- packages/syncers/src/errors.ts
Fixed incorrect `cause` handling in `SwarmNodeError` constructor:
- Replaced `super(message, error.cause);` with `super(message, { cause: error.cause });`
> Fix `SwarmNodeError` cause handling  

- .changeset/quiet-geckos-study.md
- packages/api/src/middlewares/withExpands.ts
- packages/api/src/routers/blob/helpers.ts
- packages/api/src/routers/block/helpers.ts
- packages/api/src/routers/tx/helpers.ts
- packages/api/src/utils/transformers.ts
- packages/api/src/zod-schemas.ts
- packages/api/test/__snapshots__/block.test.ts.snap
- packages/api/test/__snapshots__/tx.test.ts.snap
It adds `dataStorageReferences` field to block and transaction responses
> feat(api): add blob data storage references field to block and transaction API responses

- packages/price-feed/src/PriceFeed.ts
Fixed the broken link in packages/price-feed/src/PriceFeed.ts by removing the trailing asterisk that was causing a 404 error. The URL to the binary search implementation should not have this extra character.
> Remove trailing asterisk from GitHub URL in PriceFeed.ts

- .changeset/eleven-days-peel.md
- .changeset/fuzzy-points-pull.md
- packages/api/src/middlewares/withStatFilters.ts
This PR updates the homepage to display full daily stats for the 3-month charts.
It also improves the performance of stats fetching on the stats page by optimizing the sampling logic.
> fix(web): display full daily stats on homepage

- .changeset/lucky-toes-add.md
- apps/web/src/components/DeltaPercentage.tsx
- apps/web/src/components/Scrollable.tsx
- apps/web/src/pages/stats.tsx
> fix(web): make overall stats horizontal scrollbar always visible

- .changeset/eleven-otters-end.md
- apps/web/src/components/AppLayout/AppLayout.tsx
- apps/web/src/components/OctantBanner.tsx
It adds a banner at the top of the page announcing the upcoming Octant Epoch 8 round.
It resolves #812
> feat(web): add Octant Epoch 8 banner

- .changeset/little-frogs-know.md
- apps/web/src/components/Badges/RollupBadge.tsx
- apps/web/src/components/Cards/SurfaceCards/BlockCard.tsx
- apps/web/src/pages/blocks.tsx
It adds display of rollup counts on block cards, block table, and rollup badges to indicate multiple instances of the same rollup.
> feat(web): display rollup counts on block cards and table

- .changeset/beige-houses-sniff.md
- packages/api/src/routers/block/getByBlockId.ts
- packages/api/src/routers/block/getBySlot.ts
- packages/api/src/routers/block/helpers.ts
- packages/api/test/__snapshots__/block.test.ts.snap
- packages/api/test/block.test.ts
- packages/db/prisma/extensions/base.ts
- packages/db/prisma/zod-utils.ts
Add support for using labels (latest, oldest) as block IDs, allowing retrieval of the most recent or earliest block without needing an explicit hash or number.
> feat(api): add support for retrieving `latest` and `oldest` blocks

- .changeset/curvy-vans-share.md
- packages/api/src/routers/state/getAppState.ts
This PR switches to a LEFT JOIN, allowing the query to return app state even when no blob storage state is present.
Prevents missing app state data when blob storage state is absent.
> fix(api): resolve app state retrieval issue
