Blobscan/blobscan

.github/workflows/docker.yml
Before merging we should create a docker hub account and setup the credentials
=> ci: publish docker image

components/AppLayout/AppLayoutBottomBar.tsx, components/BlobscanLogo.tsx, components/InputSearch.tsx, pages/address/[address].tsx, pages/api/search.js, pages/blob/[id].tsx, pages/block/[block].tsx, pages/empty.tsx, pages/tx/[hash].tsx
Fixes https://github.com/Blobscan/blobscan/issues/31
=> fix: searchbar, blob data utf8 conversion, and remove hardcoded colors

.dockerignore, .env.example, .github/workflows/docker.yml, Dockerfile, README.md, docker-compose.yml, docker-entrypoint.sh, package.json, pnpm-lock.yaml
Run indexer, web and api in different containers.
=> Docker compose setup

apps/rest-api-server/api/env.ts, apps/rest-api-server/package.json, apps/web/package.json, apps/web/src/env.mjs, packages/api/package.json, packages/api/src/env.ts, packages/api/src/router/blob.ts, packages/api/src/router/indexer.ts, packages/blob-storage-manager/package.json, packages/blob-storage-manager/src/BlobStorageManager.ts, packages/blob-storage-manager/src/env.ts, packages/blob-storage-manager/src/storages/PostgresStorage.ts, packages/db/prisma/extensions/base.ts, packages/db/prisma/seed/main.ts, packages/zod/package.json, packages/zod/src/index.ts, packages/zod/src/schemas.ts, packages/zod/tsconfig.json, pnpm-lock.yaml, scripts/init-bucket.ts
It includes the following:
- Resolves #117
- Resolves #116
- New way to parse env variables  through `createEnvSchema()`. It abstracts common checks related to environment variables using Zod's schema.
- Improve blob storage manager errors description
=> Blob storage fixes

.github/workflows/ci.yml, .github/workflows/docker.yml, Dockerfile
inline variable so that it is not declared globally inside docker image and perform env validation run during runtime
=> Improve docker build skipping env validation

apps/web/src/components/AppLayout/AppLayout.tsx, apps/web/src/components/AppLayout/Banner.tsx
=> feat(web): add banner for RetroPGF

.changeset/clean-timers-argue.md, .changeset/thin-lizards-teach.md, apps/web/src/pages/blob/[hash].tsx, apps/web/src/pages/tx/[hash].tsx, packages/api/src/routers/blob/getAll.schema.ts, packages/api/src/routers/blob/getAll.ts, packages/api/src/routers/blob/getByBlobId.schema.ts, packages/api/src/routers/blob/getByBlobId.ts, packages/api/src/routers/indexer/indexData.schema.ts, packages/api/src/routers/indexer/indexData.utils.ts, packages/api/src/routers/tx/common.ts, packages/api/test/__snapshots__/blob.test.ts.snap, packages/api/test/__snapshots__/tx.test.ts.snap, packages/api/test/indexer.test.fixtures.ts, packages/blob-propagator/test/helpers.ts, packages/db/prisma/extensions/base.ts, packages/db/prisma/migrations/20240305163042_add_blob_kzg_proof_field/migration.sql, packages/db/prisma/schema.prisma, packages/db/prisma/seed/DataGenerator.ts, packages/db/prisma/seed/params.ts, packages/db/test/extensions/base-extension.test.ts, packages/test/src/fixtures/postgres/data.json
Related to https://github.com/Blobscan/blobscan-indexer.rs/pull/55
=> Add support for new blob field (kzg proof)

.changeset/eleven-items-hug.md, .changeset/gentle-snails-deny.md, packages/db/prisma/utils/dates.ts, packages/stats-syncer/src/updaters/DailyStatsUpdater.ts, packages/stats-syncer/test/DailyStatsUpdater.test.fixtures.ts, packages/stats-syncer/test/DailyStatsUpdater.test.ts, packages/stats-syncer/test/DailyStatsUpdater.test.utils.ts
=> fix(stats-syncer): avoid to aggregate data for unfinished days

.changeset/lovely-moles-jam.md, apps/web/src/components/Badges/Badge.tsx, apps/web/src/components/Badges/RollupBadge.tsx, apps/web/src/icons/mode.svg, packages/api/src/routers/indexer/indexData.utils.ts, packages/db/prisma/migrations/20240314010855_add_mode_and_zora_rollups/migration.sql, packages/db/prisma/schema.prisma
This will need database migrations before being production ready. 
Let me know if there's something we should do on that end.
=> Add Zora & Mode Rollup Badges

.changeset/nervous-feet-tan.md, apps/web/src/components/Cards/SurfaceCards/BlobTransactionCard.tsx, apps/web/src/pages/address/[address].tsx, apps/web/src/pages/blob/[hash].tsx, apps/web/src/pages/block/[id].tsx, apps/web/src/pages/txs.tsx
=> fix(web): resolve small ui issues

.changeset/seven-goats-build.md, apps/web/src/components/AppLayout/TopBarLayout/index.tsx, apps/web/src/components/NavMenusSection/NavItem.tsx, apps/web/src/components/NavMenusSection/index.tsx
=> feat(web): add mobile hamburger menu

.changeset/wet-spies-relax.md, apps/web/src/components/Badges/Badge.tsx, apps/web/src/components/Badges/RollupBadge.tsx, apps/web/src/icons/linea.svg, packages/api/src/routers/indexer/indexData.utils.ts, packages/api/src/utils/schemas.ts, packages/db/prisma/migrations/20240328215615_add_paradex_rollup/migration.sql, packages/db/prisma/migrations/20240328215617_retroactively_update_transaction_rows_rollup_field/migration.sql, packages/db/prisma/schema.prisma
- Add support for Paradex rollup 
-  Fix some style issues with Linea logos
- Apply db migration
=> feat(web): does the following:

.changeset/cuddly-kangaroos-doubt.md, packages/blob-storage-manager/src/__mocks__/SwarmStorage.ts, packages/blob-storage-manager/src/storages/SwarmStorage.ts
=> fix(blob-storage-manager): solve blob data decoding issue

.changeset/shiny-cats-appear.md, .changeset/wise-drinks-sleep.md, apps/web/src/pages/tx/[hash].tsx, apps/web/src/utils/deserializers.ts, packages/api/src/middlewares/withExpands.ts, packages/api/src/routers/block/common/serializers.ts, packages/api/src/routers/block/getAll.ts, packages/api/src/routers/block/getByBlockId.ts, packages/api/src/routers/tx/common/selects.ts, packages/api/src/routers/tx/common/serializers.ts, packages/api/src/utils/blob.ts, packages/api/test/__snapshots__/block.test.ts.snap, packages/api/test/__snapshots__/tx.test.ts.snap
It builds on top of #343 
Resolves #328.
=> feat: add blob as calldata gas fee field

.changeset/mighty-schools-allow.md, .changeset/real-taxis-hope.md, .changeset/tall-yaks-poke.md, packages/api/src/routers/indexer/indexData.ts, packages/api/test/indexer.test.ts, packages/blob-propagator/src/BlobPropagator.ts, packages/db/prisma/extensions/base.ts, packages/db/test/extensions/base-extension.test.ts
=> fix(api): make indexing procedure idempotent

.changeset/strange-poets-remember.md, packages/blob-storage-manager/package.json, packages/blob-storage-manager/src/storages/SwarmStorage.ts, pnpm-lock.yaml
=> Do non-deferred Swarm uploads

apps/docs/src/app/docs/clis/page.md, apps/docs/src/app/docs/installation/page.md, apps/docs/src/app/docs/testing/page.md, apps/docs/src/app/docs/troubleshooting/page.md
=> docs: fix typos

.changeset/gold-houses-greet.md, apps/web/src/components/ExplorerDetails.tsx
=> feat: Hide swarm expiry date when it is not configured

apps/web/sentry.edge.config.ts
This is a typo / copypaste mistake
=> fix: incorrect env var name

.changeset/few-cars-float.md, .changeset/lovely-boxes-greet.md, apps/web/src/components/Cards/SurfaceCards/BlobTransactionCard.tsx, apps/web/src/pages/address/[address].tsx, apps/web/src/pages/block/[id].tsx, apps/web/src/pages/index.tsx, apps/web/src/pages/tx/[hash].tsx, apps/web/src/pages/txs.tsx, apps/web/src/types/entities.ts, apps/web/src/types/helpers.ts, apps/web/src/utils/deserializers.ts, packages/api/src/middlewares/withExpands.ts, packages/api/src/routers/tx/common/serializers.ts
**It builds on top of #439**
This PR fixes an issue where the block timestamp isn't being displayed properly in the blob transaction card and the transaction details section.
These block timestamps are incorrect
=> fix: resolve block timestamp display issue

.github/workflows/ci.yml, .github/workflows/deploy-production.yml, .github/workflows/docker.yml
Also migrate to Feature Branch git strategy using 'main' as the main branch
This is the final step to migrate CI release workflow where we merge all PRs to the 'main' branch and then create tags/releases from it using semantic versioning.
Having a more standard way of releasing new versions and begin using Github releases for blobscan as a whole project.
=> Change workflow to release new docker images using tags + migrate to 'main' branch

apps/web/src/components/SearchInput/index.tsx
Fixes search button spinner issue. Now, the search button spinner is not being displayed after clicking any of the search result items.
Closes #476
=> fix: search button spinner issue

.changeset/hip-maps-agree.md, apps/web/src/components/ExplorerDetails.tsx, apps/web/src/pages/block/[id].tsx
Adjust blob gas price components for a better unit representation
Closes #500
=> Best gas unit

.changeset/fair-monkeys-sit.md, apps/web/src/components/Pagination.tsx
It fixes pagination buttons navigation issue
=> Fix pagination buttons

apps/web/src/components/IconButton.tsx, apps/web/src/components/NavArrows.tsx
Smaller nav arrows
Before:
After:
=> chore: Smaller NavArrows

.changeset/six-bees-rhyme.md, apps/web/src/components/NavArrows.tsx, apps/web/src/pages/block/[id].tsx, apps/web/src/pages/tx/[hash].tsx, packages/api/src/routers/tx/getNextTxFromSender.ts, packages/api/src/routers/tx/index.ts
Added navigation arrows to the transaction page
=> Added navigation arrows to the transaction page

apps/web/src/components/Link.tsx
Refactors Link component and enhances spacing.
Before:
After:
=> chore: simplify link

.changeset/rare-candles-scream.md, apps/web/src/pages/blob/[hash].tsx
Fixed the transaction hash overlap in the blob page
Closes #550
=> Fixed the transaction hash overlap in the blob page

.changeset/cool-dingos-visit.md, apps/web/src/components/Charts/Block/DailyAvgBlobFeeChart.tsx, apps/web/src/components/Charts/Block/DailyAvgBlobGasPriceChart.tsx, apps/web/src/components/Charts/Block/DailyBlobFeeChart.tsx, apps/web/src/components/Charts/Block/DailyBlobGasComparisonChart.tsx, apps/web/src/components/Charts/Block/DailyBlobGasUsedChart.tsx, apps/web/src/components/Charts/Transaction/DailyAvgMaxBlobGasFeeChart.tsx, packages/eth-format/index.ts
Display tooltip values in their best unit
Closes  #574
Before:
After:
=> refactor: Update chart tooltips to use best unit

.changeset/silent-taxis-admire.md, apps/web/src/components/Dropdown/index.tsx, apps/web/src/components/Filters/RollupFilter.tsx, apps/web/src/components/Filters/TimestampFilter.tsx, apps/web/src/components/Filters/index.tsx, apps/web/src/components/PaginatedTable/index.tsx
- Fixed the overflow issue in the filters reducing the input elements width and improving/fixing the responsiveness of all the inputs
Closes #549 
https://github.com/user-attachments/assets/f78f7235-2f43-4439-a318-b12edd47a6ed
https://github.com/user-attachments/assets/31020aa4-937a-4124-a363-fd92daa6d65f
=> fix: `Filters` overflow & Responsiveness issues

apps/web/src/components/Cards/SurfaceCards/BlobCard.tsx, apps/web/src/components/Cards/SurfaceCards/BlockCard.tsx
This PR ensures more consistent spacing for the elements within the cards on the home page, improving overall layout uniformity.
Before:
After:
=> refactor: Update styling in BlobCard and BlockCard components

.github/workflows/ci.yml, .github/workflows/nextjs-bundle-analysis.yml, tooling/github/setup-db/action.yml, tooling/github/setup/action.yml
=> chore(ci): fix GitHub action workflows

clis/stats-aggregation-cli/test/commands/__snapshots__/overall.test.ts.snap, clis/stats-aggregation-cli/test/commands/overall.test.ts, packages/api/src/context.ts, packages/api/test/helpers.ts, packages/api/test/indexer.test.ts, packages/api/test/tx.test.ts, packages/blob-storage-manager/src/blob-storage-manager.ts, packages/db/test/__snapshots__/base-extension.test.ts.snap, packages/db/test/base-extension.test.ts, packages/test/src/helpers.ts
It fixes  some UTs snapshot mismatches by sorting results by category and rollup when possible and index-related tests
=> test: fix tests

apps/docs/src/components/Layout.jsx
=> docs: order sections

apps/web/src/env.mjs
Fixes the type errors in the `env.mjs` file
=> fix: createEnv type error

packages/api/src/context.ts, packages/api/src/posthog.ts
Refactor PostHog to handle short-lived environments
https://posthog.com/docs/libraries/next-js
#571
=> fix: Refactor PostHog to handle short-lived environments

.changeset/late-dolphins-fly.md, apps/web/src/components/AppLayout/TopBarLayout/index.tsx, apps/web/src/components/GitcoinBanner.tsx
It adds Gitcoin round 22 banner
=> feat(web): add gitcoin banner

apps/docs/src/app/docs/code-of-conduct/page.md, apps/docs/src/app/docs/installation/page.md, apps/docs/src/app/docs/running-blobscan-k8s/page.md
Hello
I fixed several spelling issues.
=> Docs fix spelling issues

apps/docs/src/app/docs/installation/page.md, packages/blob-storage-manager/test/storages/FileSystemStorage.test.ts, packages/optimism-decoder/src/download.ts
=> chore: fix some typos in comments

.changeset/silent-dolls-sniff.md, packages/api/src/context.ts, packages/api/src/posthog.ts
Adds URL filtering for `PostHog` tracking
Closes  #614
=> feat(api): add URL filtering for PostHog tracking

apps/docs/src/app/docs/background-jobs/page.md
Updated the documentation to correct a grammatical error in the `page.md` file by replacing "checkout" with "check out" for improved readability and accuracy.
This change improves the clarity and professionalism of the documentation.
=> Fix typo in documentation

apps/docs/src/app/docs/background-jobs/page.md, apps/docs/src/app/docs/clis/page.md, apps/docs/src/app/docs/codebase-overview/page.md
The previous link has expired and has been replaced with the latest address.
=> chore: fix 404 status URL

apps/web/src/components/NavArrows.tsx
Updates NavArrows component to conditionally set cursor style based on href availability
=> NavArrows set cursor style based on href availability

packages/api/src/blob-parse/optimism.ts
1. **File**: `packages/api/src/blob-parse/optimism.ts`
- Fixed a typo by changing "ocurrence" to "occurrence".
- Improved code accuracy by fixing the typographical error.
- Enhanced the clarity and professionalism of the codebase.
=> typo-Update optimism.ts

.changeset/olive-ligers-watch.md, apps/web/src/components/InfoField.tsx, apps/web/src/components/InfoGrid.tsx, apps/web/src/icons/info.svg, apps/web/src/pages/block/[id].tsx
Adds a help tooltip to each field in the block details page
#433
=> Add help tooltip block

apps/docs/src/app/docs/storages/page.md
I’ve updated the repository to use the correct term "PostgreSQL" instead of "Postgres" throughout the code and documentation.
The term "**PostgreSQL**" is the official name of the database, and using it consistently ensures better accuracy and clarity in our work.
=> docs: Corrected Term Usage for Database Update page.md

clis/blob-propagation-jobs-cli/src/commands/create.ts, packages/api/src/routers/blob/getBlobDataByBlobId.ts
=> chore: fix some typos in comment

packages/api/src/routers/blob/createWeaveVMReferences.ts
=> fix(api): correct error handling in weavevm creation procedure

package.json, packages/blob-propagator/CHANGELOG.md, packages/blob-storage-manager/CHANGELOG.md, packages/blob-storage-manager/src/BlobStorageManager.ts
1. **`package.json`**:
- Corrected `workspaceProtocool` to `workspaceProtocol`.
2. **`CHANGELOG.md`** in `blob-propagator` package:
- Fixed "enviroment" to "environment" in changelog entries.
3. **`CHANGELOG.md`** in `blob-storage-manager` package:
- Corrected "enviroment" to "environment".
4. **`BlobStorageManager.ts`**:
- Fixed spelling errors in variable names:
- `selectdAvailableStorageNames` → `selectedAvailableStorageNames`.
These changes address minor typos to enhance code quality and ensure better comprehension for developers.
=> Fix spelling errors across multiple files

apps/web/CHANGELOG.md
1. **File:** `/apps/web/CHANGELOG.md`
- Fixed `Splited` to `Split` (Line 483)
- EImproved the documentation's clarity and professional tone.
- Corrected small grammatical errors to enhance comprehension.
=> Corrected typos

packages/syncers/test/__snapshots__/BaseSyncer.test.ts.snap, packages/syncers/test/__snapshots__/PeriodicUpdater.test.ts.snap, packages/syncers/test/__snapshots__/StatsSyncer.test.ts.snap
This pull request contains changes to improve clarity, correctness and structure.
=> fix: typos in documentation files

.changeset/sharp-crabs-build.md, packages/blob-propagator/src/utils.ts, packages/blob-propagator/test/__snapshots__/storage-workers.test.ts.snap, packages/blob-propagator/test/storage-workers.test.ts, packages/blob-storage-manager/src/storages/SwarmStorage.ts, packages/logger/src/index.ts
It improves error formatting across different packages
=> fix: improve error handling

README.md
=> docs (README.md): fix Scroll logo

.changeset/young-teachers-drive.md, apps/web/src/pages/api/blob-data.ts, apps/web/src/pages/blob/[hash].tsx
Fixes an issue where the response body for `.bin` blob data files was not being correctly parsed.
=> fix(web): resolve blob data display issue

.changeset/orange-olives-camp.md, packages/blob-storage-manager/src/storages/SwarmStorage.ts
Update `Chunkstorm` service endpoint to match changes in https://github.com/Blobscan/chunkstorm/pull/3
=> refactor(api): Update Chunkstorm endpoint

apps/rest-api-server/src/utils.ts, apps/web/src/utils/web3.ts, packages/env/index.ts, packages/rollups/src/index.ts
=> fix: Hoodi support in all packages

.changeset/strange-cups-rhyme.md, apps/web/src/components/OctantBanner.tsx
Update Octant banner message to reflect the start of the new round
=> feat(web): update Octant banner message

.changeset/red-mangos-add.md, apps/web/src/components/Displays/BlobGasUsageDisplay.tsx, apps/web/src/pages/block/[id].tsx, apps/web/src/pages/blocks.tsx
=> fix(web): inline blob gas target when compact is enable

.changeset/afraid-pandas-flash.md, .changeset/chatty-files-agree.md, .changeset/famous-frogs-knock.md, .changeset/lazy-icons-report.md, apps/web/src/components/Cards/SurfaceCards/BlobTransactionCard.tsx, apps/web/src/pages/blob/[hash].tsx, apps/web/src/pages/blocks.tsx, apps/web/src/pages/txs.tsx, packages/api/src/routers/blob/helpers.ts
=> feat(web): display blob index and storage badges in all subtables or subsections

apps/web/src/components/Rotable.tsx, apps/web/src/components/SidebarNavigationMenu.tsx
=> feat(web): add blob, block and tx icons to sidebar

.changeset/four-drinks-raise.md, .changeset/friendly-vans-call.md, .changeset/great-cougars-sneeze.md, apps/web/src/pages/api/blob-data.ts, apps/web/src/pages/blob/[hash].tsx, packages/api/src/utils/transformers.ts, packages/api/test/__snapshots__/blob.test.ts.snap, packages/api/test/__snapshots__/block.test.ts.snap, packages/api/test/__snapshots__/tx.test.ts.snap, packages/blob-storage-manager/setup.ts, packages/blob-storage-manager/src/storages/SwarmStorage.ts
=> fix: resolve swarm blob data fetching issues

.changeset/fresh-trainers-explain.md, apps/web/src/components/Indicators/NetworkIndicators.tsx
=> feat(web): add icon to blob price indicator

.changeset/breezy-keys-appear.md, .changeset/dull-roses-shout.md, apps/web/src/pages/blob/[hash].tsx
=> fix(web): align blob and transaction references and display compact rollup badge on each row

.changeset/forty-laws-chew.md, apps/web/src/components/Displays/BlobUsageDisplay.tsx, apps/web/src/utils/bytes.ts, apps/web/src/utils/number.ts
=> fix(web): prevent round up of formatted number amounts

.changeset/eighty-boxes-invent.md, apps/web/src/components/AppLayout/BottomBarLayout/index.tsx, apps/web/src/components/BlobscanVersionInfo.tsx, apps/web/src/components/Indicators/SyncIndicators.tsx
It displays donation message along with donation address on the footer
=> feat(web): display donation address

.changeset/plenty-plants-enjoy.md, apps/web/src/components/SlidableList.tsx, apps/web/src/pages/index.tsx
It improves the animation behavior of the `SlidableList`  component on the home page.
The updated animation logic smoothens item entry and exit transitions, reducing clunkiness and making the list feel more natural and responsive.
=> fix(web): smoothen `SlidableList` animation on home page

.changeset/heavy-masks-swim.md, apps/rest-api-server/src/blob-propagator.ts, apps/rest-api-server/src/blob-storages.ts
=> fix(blob-propagator): resolve issue where primary storage was created even if it was not enabled

apps/rest-api-server/src/index.ts, packages/api/src/context.ts, packages/api/src/middlewares/withAuthed.ts, packages/api/src/procedures/authed.ts, packages/api/src/utils/auth.ts, packages/api/test/helpers.ts
=> fix(api): auth admin

.changeset/smooth-taxis-battle.md, packages/api/src/routers/indexer/indexData.ts, packages/api/test/indexer/__snapshots__/indexData.test.ts.snap, packages/api/test/indexer/indexData.test.ts
=> fix(api): ensure error is thrown when indexing runs without a blob propagator

.changeset/chilled-dodos-run.md, .changeset/clever-zebras-agree.md, apps/web/src/components/Badges/StatusBadge.tsx, apps/web/src/components/Indicators/NetworkIndicators.tsx
It hides eth usd price indicator on testnet chains and removes network name
=> feat(web): update header indicators
